/* Workout fueling recipes and assignments. Stored inside the main app state. */
(()=>{
'use strict';
const uid=()=>crypto.randomUUID();
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const starter=[
 {id:'gel-maple-30',name:'Maple Salt Gel',type:'gel',servings:1,carbs:30,sodium:200,caffeine:0,fluidOz:0,ingredients:[{name:'Pure maple syrup',amount:45,unit:'g'},{name:'Fine table salt',amount:.5,unit:'g'},{name:'Lemon or lime juice',amount:5,unit:'g'},{name:'Water',amount:10,unit:'g'}],notes:'About 60 g total mixture. Thin with a few extra grams of water if needed. Estimated nutrition varies with the syrup label.'},
 {id:'gel-honey-maple-30',name:'Honey–Maple Gel',type:'gel',servings:1,carbs:31,sodium:250,caffeine:0,fluidOz:0,ingredients:[{name:'Honey',amount:25,unit:'g'},{name:'Pure maple syrup',amount:15,unit:'g'},{name:'Fine table salt',amount:.64,unit:'g'},{name:'Water',amount:15,unit:'g'}],notes:'A smoother mixed-sugar option. Warm the water slightly, stir, then cool before filling a flask.'},
 {id:'gel-citrus-35',name:'Budget Citrus Gel',type:'gel',servings:1,carbs:35,sodium:295,caffeine:0,fluidOz:0,ingredients:[{name:'Table sugar',amount:35,unit:'g'},{name:'Fine table salt',amount:.75,unit:'g'},{name:'Lemon or lime juice',amount:8,unit:'g'},{name:'Warm water',amount:18,unit:'g'}],notes:'Lowest-cost formula. Dissolve completely and cool. Sucrose supplies both glucose and fructose after digestion.'},
 {id:'gel-dual-40',name:'High-Carb Dual-Source Gel',type:'gel',servings:1,carbs:40,sodium:255,caffeine:0,fluidOz:0,ingredients:[{name:'Maltodextrin',amount:22,unit:'g'},{name:'Fructose powder',amount:18,unit:'g'},{name:'Trisodium citrate dihydrate',amount:1.1,unit:'g'},{name:'Lemon or lime juice',amount:5,unit:'g'},{name:'Water',amount:25,unit:'g'}],notes:'Approximately a 1:0.8 glucose-source-to-fructose blend for higher hourly carbohydrate targets. Sodium estimate assumes trisodium citrate dihydrate is about 23.4% sodium.'},
 {id:'drink-light-30',name:'Light Training Drink — 24 oz',type:'drink',servings:1,carbs:30,sodium:510,caffeine:0,fluidOz:24,ingredients:[{name:'Table sugar',amount:30,unit:'g'},{name:'Fine table salt',amount:1.3,unit:'g'},{name:'Lemon or lime juice',amount:15,unit:'g'},{name:'Water',amount:695,unit:'mL'}],notes:'For shorter or easier sessions when most carbohydrate comes from food or gels. Adjust citrus to taste.'},
 {id:'drink-standard-60',name:'Standard Carb Drink — 24 oz',type:'drink',servings:1,carbs:60,sodium:590,caffeine:0,fluidOz:24,ingredients:[{name:'Table sugar',amount:60,unit:'g'},{name:'Fine table salt',amount:1.5,unit:'g'},{name:'Lemon or lime juice',amount:15,unit:'g'},{name:'Water',amount:680,unit:'mL'}],notes:'A simple long-run bottle. Sip gradually rather than drinking the entire bottle at once.'},
 {id:'drink-dual-90',name:'Marathon Dual-Source Drink — 34 oz',type:'drink',servings:1,carbs:90,sodium:705,caffeine:0,fluidOz:34,ingredients:[{name:'Maltodextrin',amount:50,unit:'g'},{name:'Fructose powder',amount:40,unit:'g'},{name:'Fine table salt',amount:1.8,unit:'g'},{name:'Lemon or lime juice',amount:20,unit:'g'},{name:'Water',amount:960,unit:'mL'}],notes:'A 1:0.8 high-carbohydrate blend for long marathon-specific sessions. Do not begin here: progress through 60–70 g/hour first and monitor GI response.'},
 {id:'drink-hot-60',name:'High-Sodium Carb Drink — 24 oz',type:'drink',servings:1,carbs:60,sodium:1015,caffeine:0,fluidOz:24,ingredients:[{name:'Table sugar',amount:60,unit:'g'},{name:'Trisodium citrate dihydrate',amount:3,unit:'g'},{name:'Fine table salt',amount:.8,unit:'g'},{name:'Lemon or lime juice',amount:15,unit:'g'},{name:'Water',amount:680,unit:'mL'}],notes:'Hot-weather/high-sweat option. This is not a default for every run. Sodium estimate assumes trisodium citrate dihydrate is about 23.4% sodium.'}
];
state.schemaVersion=Math.max(state.schemaVersion||7,8);
state.fueling=state.fueling&&Array.isArray(state.fueling.recipes)&&Array.isArray(state.fueling.assignments)?state.fueling:{version:1,recipes:[],assignments:[]};
if(!state.fueling.recipeSeedV2){state.fueling.recipes=state.fueling.recipes.filter(r=>!['starter-gel','starter-drink'].includes(r.id));starter.forEach(r=>{if(!state.fueling.recipes.some(x=>x.id===r.id))state.fueling.recipes.push(r)});state.fueling.recipeSeedV2=true;save()}
const F=()=>state.fueling;
const host=document.createElement('section');host.className='fuel-lab';document.getElementById('p-goals').prepend(host);
const dlg=document.createElement('dialog');dlg.className='fuel-dialog';document.body.append(dlg);
const persist=()=>{save();render();};
function btn(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;return b}
function modal(title){dlg.replaceChildren();dlg.append(btn('Close',()=>dlg.close(),'fuel-close'));const h=document.createElement('h2');h.textContent=title;dlg.append(h);if(!dlg.open)dlg.showModal();return dlg}
function field(parent,label,type,value){const l=document.createElement('label');l.textContent=label;const x=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')x.type=type;x.value=value??'';x.setAttribute('aria-label',label);l.append(x);parent.append(l);return x}
function select(parent,label,items,value){const l=document.createElement('label');l.textContent=label;const x=document.createElement('select');x.setAttribute('aria-label',label);items.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;x.append(o)});x.value=value;l.append(x);parent.append(l);return x}
function workoutName(id){const w=state.running?.workouts?.find(x=>x.id===id);return w?`${w.date} · ${w.title}`:'Workout removed'}
function recipeName(id){return F().recipes.find(x=>x.id===id)?.name||'Recipe removed'}
function render(){
 host.replaceChildren();const h=document.createElement('h3');h.textContent='WORKOUT FUELING LAB';host.append(h);
 const p=document.createElement('p');p.textContent=`${F().recipes.length} recipes · ${F().assignments.length} workout plans · saved with your normal cloud copy`;host.append(p);
 const actions=document.createElement('div');actions.className='fuel-actions';actions.append(btn('Recipes & batch calculator',recipes),btn('Plan workout fueling',assign),btn('Upcoming fuel plans',plans));host.append(actions);
 const pending=F().recipes.filter(r=>r.pending).length;if(pending){const n=document.createElement('small');n.textContent=`${pending} starter formula${pending===1?' is':'s are'} still marked as a placeholder.`;host.append(n)}
}
function recipes(){const m=modal('Fuel recipes');m.append(btn('＋ New recipe',()=>editRecipe()));if(!F().recipes.length){const p=document.createElement('p');p.textContent='No recipes yet.';m.append(p)}
 F().recipes.forEach(r=>{const c=document.createElement('article');c.className='fuel-card';c.innerHTML=`<strong>${safe(r.name)}</strong>${r.pending?'<span class="fuel-pending">PLACEHOLDER</span>':''}<p>${r.carbs}g carbs · ${r.sodium}mg sodium · ${r.caffeine||0}mg caffeine${r.fluidOz?' · '+r.fluidOz+' oz':''} per serving</p>`;c.append(btn('Scale batch',()=>scale(r.id)),btn('Edit',()=>editRecipe(r.id)),btn('Delete',()=>{if(confirm('Delete this recipe and its workout assignments?')){F().recipes=F().recipes.filter(x=>x.id!==r.id);F().assignments=F().assignments.filter(x=>x.recipeId!==r.id);persist();recipes()}}));m.append(c)})}
function editRecipe(id){const old=F().recipes.find(x=>x.id===id),r=old?JSON.parse(JSON.stringify(old)):{id:uid(),name:'',type:'gel',servings:1,carbs:0,sodium:0,caffeine:0,fluidOz:0,ingredients:[],notes:'',pending:false};const m=modal(old?'Edit recipe':'New recipe');const name=field(m,'Recipe name','text',r.name),type=select(m,'Type',[['gel','Gel'],['drink','Drink'],['meal','Pre-run meal'],['other','Other']],r.type),serv=field(m,'Recipe yield (servings)','number',r.servings),carbs=field(m,'Carbs per serving (g)','number',r.carbs),sodium=field(m,'Sodium per serving (mg)','number',r.sodium),caf=field(m,'Caffeine per serving (mg)','number',r.caffeine),fluid=field(m,'Fluid per serving (oz)','number',r.fluidOz),ings=field(m,'Ingredients — one per line: name | amount | unit','textarea',r.ingredients.map(x=>`${x.name} | ${x.amount} | ${x.unit}`).join('\n')),notes=field(m,'Preparation and use notes','textarea',r.notes);
 m.append(btn('Save recipe',()=>{const parsed=ings.value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [n,a,u]=line.split('|').map(x=>x.trim());return {name:n,amount:Number(a),unit:u||''}});if(!name.value.trim()||+serv.value<=0||parsed.some(x=>!x.name||!Number.isFinite(x.amount)||x.amount<=0)){toast('Add a name, yield, and valid ingredient lines');return}Object.assign(r,{name:name.value.trim(),type:type.value,servings:+serv.value,carbs:Math.max(0,+carbs.value),sodium:Math.max(0,+sodium.value),caffeine:Math.max(0,+caf.value),fluidOz:Math.max(0,+fluid.value),ingredients:parsed,notes:notes.value.trim(),pending:false});const i=F().recipes.findIndex(x=>x.id===r.id);if(i<0)F().recipes.push(r);else F().recipes[i]=r;persist();recipes()}))}
function scale(id){const r=F().recipes.find(x=>x.id===id),m=modal('Scale '+r.name),count=field(m,'Servings to make','number',r.servings||1),out=document.createElement('div');out.className='fuel-scale';m.append(out);function calc(){const n=Math.max(0,+count.value||0),factor=n/(r.servings||1);out.innerHTML=`<h3>${g(n)} servings</h3>${r.ingredients.map(x=>`<p><strong>${safe(g(x.amount*factor))} ${safe(x.unit)}</strong> ${safe(x.name)}</p>`).join('')}<p class="fuel-total">Batch total: ${g(r.carbs*n)}g carbs · ${g(r.sodium*n)}mg sodium · ${g(r.caffeine*n)}mg caffeine${r.fluidOz?' · '+g(r.fluidOz*n)+' oz':''}</p>`}function g(n){return Math.round(n*100)/100}count.oninput=calc;calc()}
function assign(existing){const a=existing?F().assignments.find(x=>x.id===existing):null,m=modal(a?'Edit workout fueling':'Plan workout fueling');const workouts=(state.running?.workouts||[]).filter(w=>w.status!=='skipped').sort((x,y)=>x.date.localeCompare(y.date));if(!workouts.length||!F().recipes.length){const p=document.createElement('p');p.textContent='Add a running plan and at least one recipe first.';m.append(p);return}const wo=select(m,'Workout',workouts.map(w=>[w.id,`${w.date} · ${w.title}`]),a?.workoutId||workouts.find(w=>w.date>=todayKey())?.id||workouts[0].id),recipe=select(m,'Recipe',F().recipes.map(r=>[r.id,r.name]),a?.recipeId||F().recipes[0].id),serv=field(m,'Planned servings','number',a?.servings||1),interval=field(m,'Use every (minutes)','number',a?.intervalMin||30),carbs=field(m,'Target carbs per hour (g)','number',a?.targetCarbsHr||60),sodium=field(m,'Target sodium per hour (mg)','number',a?.targetSodiumHr||700),fluid=field(m,'Target fluid per hour (oz)','number',a?.targetFluidHr||20),notes=field(m,'Plan notes','textarea',a?.notes||'');m.append(btn('Save fueling plan',()=>{if(+serv.value<=0||+interval.value<=0){toast('Servings and interval must be positive');return}const v={id:a?.id||uid(),workoutId:wo.value,recipeId:recipe.value,servings:+serv.value,intervalMin:+interval.value,targetCarbsHr:Math.max(0,+carbs.value),targetSodiumHr:Math.max(0,+sodium.value),targetFluidHr:Math.max(0,+fluid.value),actualServings:a?.actualServings??null,gi:a?.gi||'',notes:notes.value.trim()};const i=F().assignments.findIndex(x=>x.id===v.id);if(i<0)F().assignments.push(v);else F().assignments[i]=v;persist();plans()}))}
function plans(){const m=modal('Workout fuel plans');if(!F().assignments.length){const p=document.createElement('p');p.textContent='Nothing assigned yet.';m.append(p)}F().assignments.slice().sort((a,b)=>workoutName(a.workoutId).localeCompare(workoutName(b.workoutId))).forEach(a=>{const r=F().recipes.find(x=>x.id===a.recipeId),c=document.createElement('article');c.className='fuel-card';c.innerHTML=`<strong>${safe(workoutName(a.workoutId))}</strong><p>${safe(recipeName(a.recipeId))} · ${a.servings} serving${a.servings===1?'':'s'} · every ${a.intervalMin} min</p><p>Targets: ${a.targetCarbsHr}g carbs/hr · ${a.targetSodiumHr}mg sodium/hr · ${a.targetFluidHr}oz/hr</p>${a.actualServings!==null?`<p>Actual: ${a.actualServings} servings${a.gi?' · GI: '+safe(a.gi):''}</p>`:''}`;c.append(btn('Log result',()=>logResult(a.id)),btn('Edit',()=>assign(a.id)),btn('Delete',()=>{F().assignments=F().assignments.filter(x=>x.id!==a.id);persist();plans()}));m.append(c)})}
function logResult(id){const a=F().assignments.find(x=>x.id===id),m=modal('Log fueling result'),serv=field(m,'Actual servings consumed','number',a.actualServings??a.servings),gi=select(m,'GI result',[['','Not rated'],['great','Great'],['okay','Okay'],['poor','Poor']],a.gi||''),notes=field(m,'What worked or needs changing','textarea',a.resultNotes||'');m.append(btn('Save result',()=>{a.actualServings=Math.max(0,+serv.value);a.gi=gi.value;a.resultNotes=notes.value.trim();persist();plans()}))}
window.FuelingTest={state:F,workoutName};render();
})();
